me: "Tests: PostgreSQL"

on:
  - pull_request
  - push

jobs:
  pgsql:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    services:
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers
      pgsql:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "phpunit"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_pgsql

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./phpunit.php --configuration ./build/travis-ci.xml

      - name: PostgreSQL service logs
        run: docker logs ${{ job.services.pgsql.id }}
        if: always()
